- name: Add Docker GPG key (Debian-Based)
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg
    state: present

- name: Add Docker Repository (Debian-Based)
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] }} stable
    state: present

- name: Install docker packages (Debian-Based)
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true
