- name: Add Docker Repository (RedHat-Based)
  yum_repository:
    name: docker-ce
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/$releasever/$basearch/stable
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg

- name: Install docker packages (RedHat-Based)
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest