- name: Init
  hosts: all
  become: yes
  roles:
    - init

- name: CA Certs
  hosts: all
  become: yes
  roles:
    - ca-certs

- name: Docker
  hosts: all
  become: yes
  roles:
    - docker

- name: Vector
  hosts: vector
  become: yes
  roles:
    - vector

- name: Loki
  hosts: loki
  become: yes
  roles:
    - loki

